<template>
  <div>
    <div id="categorybox"><div class="allkind"><header class="clearfix rela top bgfff"><div id="1" class="fl sort nav-sort ft13 bold cur"><a href="#tab1"><span>分类</span></a></div> <div id="2" class="fl brand nav-sort ft13 bold"><a href="#tab2"><span>品牌</span></a></div> <a href="https://wap.epet.com/search.html?pet_type=dog&amp;fw=0"><img src="//static.epetbar.com/static_web/wap/src/images/background/search-ico.png" class="abs search"></a></header> <div id="tab1" class="kindbox"><div class="leftbox bgfff scrollbar-none"><div><ul><li data-id="88888" class="ftc bgfff on">为您推荐</li><li data-id="5" class="ftc bgfff">狗狗主粮</li><li data-id="6" class="ftc bgfff">狗狗零食</li><li data-id="55" class="ftc bgfff">狗狗服饰</li><li data-id="4311" class="ftc bgfff">狗狗窝垫</li><li data-id="54" class="ftc bgfff">狗狗生活</li><li data-id="53" class="ftc bgfff">狗狗玩具</li><li data-id="48" class="ftc bgfff">狗狗保健</li><li data-id="49" class="ftc bgfff">狗狗医疗</li><li data-id="2652" class="ftc bgfff">狗狗牵引</li><li data-id="2651" class="ftc bgfff">狗狗美容</li><li data-id="3895" class="ftc bgfff">狗狗周边</li><li data-id="4315" class="ftc bgfff">狗狗清洁</li></ul></div></div> <div class="rightbox bgfff scrollbar-none"><div class="sort-detail-list"><!----> <!----> <div class="sort-recom bgfff"><div class="hot-recom bbtf3"><a href="javascript:;" class="title c999 db ft12 mt10 pl5">
      热门分类
      <!----></a> <ul class="clearfix"><li class="fl mt10"><a href="https://wap.epet.com/goodslist.html?id_param=cateid_7&amp;fw=0" class="db"><div class="rela loadimg-nofixed"><img class="w100 image" src="https://img2.epetbar.com/nowater/2016-07/21/14/0f972761c08a37c8baff88fa9302053d.jpg@!300w-b" lazy="loaded"></div> <p class="ftc ft12 mt10 c333">进口狗粮</p></a></li><li class="fl mt10"><a href="https://wap.epet.com/goodslist.html?id_param=cateid_3555&amp;fw=0" class="db"><div class="rela loadimg-nofixed"><img class="w100 image" src="https://img2.epetbar.com/nowater/2017-05/12/10/f38b8a4245c34c33061d04ad1e8009dd.jpg@!300w-b" lazy="loaded"></div> <p class="ftc ft12 mt10 c333">国产狗粮</p></a></li><li class="fl mt10"><a href="https://wap.epet.com/goodslist.html?id_param=cateid_10&amp;fw=0" class="db"><div class="rela loadimg-nofixed"><img class="w100 image" src="https://img2.epetbar.com/nowater/2017-05/26/10/2eeb97d6268f555de24ec370fd0de2ad.jpg@!300w-b" lazy="loaded"></div> <p class="ftc ft12 mt10 c333">磨牙洁齿</p></a></li><li class="fl mt10"><a href="https://wap.epet.com/goodslist.html?id_param=cateid_521&amp;fw=0" class="db"><div class="rela loadimg-nofixed"><img class="w100 image" src="https://img2.epetbar.com/nowater/cates/2014-03/24/81f4ac6b5b31143c056046bd9dc14b9e.jpg@!300w-b" lazy="loaded"></div> <p class="ftc ft12 mt10 c333">体内驱虫</p></a></li><li class="fl mt10"><a href="https://wap.epet.com/goodslist.html?id_param=cateid_413&amp;fw=0" class="db"><div class="rela loadimg-nofixed"><img class="w100 image" src="https://img2.epetbar.com/nowater/2017-05/04/16/fd206e6489657294e9067d349ea297f1.jpg@!300w-b" lazy="loaded"></div> <p class="ftc ft12 mt10 c333">强化免疫</p></a></li><li class="fl mt10"><a href="https://wap.epet.com/goodslist.html?id_param=cateid_756&amp;fw=0" class="db"><div class="rela loadimg-nofixed"><img class="w100 image" src="https://img2.epetbar.com/nowater/2016-08/20/14/8095e54e9414a06705acb7471eac7629.jpg@!300w-b" lazy="loaded"></div> <p class="ftc ft12 mt10 c333">肠胃调理</p></a></li> <!----><!----><!----><!----><!----><!----> <!----><!----><!----><!----><!----><!----></ul></div></div></div></div></div> <!----></div></div>
  </div>
</template>
<script>
  export default{
    data(){
      return {}
    }
  }
</script>
<style lang="stylus" rel="stylesheet/stylus">

</style>
